using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Class1;
namespace Class1
{
    [TestFixture]
    public class Tests_for_Class1
    {
        [Test]
        public void Test_for_CharCount()
        {
            Assert.Fail("autogenerated");
        }
    }
}