using NUnit.Framework;
using Class4;
using Class5;
namespace Class5
{
    [TestFixture]
    public class Tests_for_Class5
    {
        [Test]
        public void Test_for_Method()
        {
            Assert.Fail("autogenerated");
        }
    }
}