using System;
using System.Collections.Generic;
using NUnit.Framework;
using Class3;
namespace Class3
{
    [TestFixture]
    public class Tests_for_Class3
    {
        [Test]
        public void Test_for_FirstMethod()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Test_for_SecondMethod()
        {
            Assert.Fail("autogenerated");
        }
    }
}