using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Class2;
namespace Class2
{
    [TestFixture]
    public class Tests_for_Class2
    {
        [Test]
        public void Test_for_Counter()
        {
            Assert.Fail("autogenerated");
        }
    }
}