using NUnit.Framework;
using Class4;
using Class5;
namespace Class4
{
    [TestFixture]
    public class Tests_for_Class4
    {
        [Test]
        public void Test_for_Method1()
        {
            Assert.Fail("autogenerated");
        }
    }
}